### ISSUE TITLE
Feature: Integration for another extension like related news

### ISSUE THREAD

**Issue by jankout** [fritzmg/contao-news-sorting#2]
Hello, I would like to use your great and useful extension for the extension [related news](https://contao.org/en/extension-list/view/news_related.30050006.en.html) to sort the news list by another criterions. Is it possible to implement it?

**Comment by fritzmg** [comment]
It's difficult to make such modules compatible with each other. And in this case it does not make sense to make them compatible - you should post a feature request [here](https://github.com/1up-lab/contao-news_related/issues) to be able to have the same sort options like in this extension (and in Contao 4.5+) in their module.

**Comment by jankout** [comment]
Thank you.
