### ISSUE TITLE
Top level sorting

### ISSUE THREAD

**Issue by skolarianer** [fritzmg/contao-news-sorting#3]
If I select two or more news archives in a newslist module, the news are sorted separately for each news archive and are printed consecutively.
Would be very cool if this extension could sort the news on the top level across all archives.

EDIT: Contao 4.4.8 + codefog/contao-news_categories (if that matters)

**Comment by fritzmg** [comment]
Weird, that should not happen. I'll have a look.

**Comment by skolarianer** [comment]
Oh no, sorry! My fault. Everything is fine. *blush*
I used some additional demo data and didn’t recognize the year of the news. :man_facepalming: 

EDIT: I’ve sent you an item from your amazon wishlist to apologize.

**Comment by fritzmg** [comment]
Hehe, that's fine, no need for an apology ;)
