### ISSUE TITLE
More incompatible extensions

### ISSUE THREAD

**Issue by wschwaiger** [fritzmg/contao-news-sorting#7]
If I am right please add the following extension to the conflict list.

heimrichhannot/contao-slick-bundle

Many thanks. I'll keep testing.

**Comment by fritzmg** [comment]
Why is `heimrichhannot/contao-slick-bundle` incompatible with this extension?

**Comment by wschwaiger** [comment]
At the moment it is just a hunch. But I can not see the sorting option on the news settings page. I try to verify at the moment, why the sorting option is not showing up. Any other idea maybe, why this could be?

**Comment by fritzmg** [comment]
> But I can not see the sorting option on the news settings page.

What exactly do you mean by that? Are you trying to use the custom sorting functionality? For that you need to set the sorting option to "Sorting value" and then apply:

![image](https://user-images.githubusercontent.com/4970961/146045086-53abd50c-eede-4e69-853d-39e0b7d07c28.png)

See also the [README](https://github.com/fritzmg/contao-news-sorting).

**Comment by wschwaiger** [comment]
No, no. Not at all. I see no checkbox in the backend settings page - there should be 'Experteneinstellungen'. See attached. And this must be caused by another extension. Or am I  on the wrong path?

![Bildschirmfoto 2021-12-14 um 18 12 57](https://user-images.githubusercontent.com/458603/146047050-3ee9f58b-45ef-4326-a1dd-a45f093e5b65.png)

**Comment by fritzmg** [comment]
> No, no. Not at all. I see no checkbox in the backend settings page - there should be 'Experteneinstellungen'. See attached. And this must be caused by another extension. Or am I on the wrong path?

That looks like the settings page for the news archive. There are no expert settings in the news archive (unless an extension provides it). This extension does not provide any additional settings for the news archive.

What is is that you are searching for or trying to do?

**Comment by wschwaiger** [comment]
Ok. Sorry for the confusion. Where do I activate the sorting option with your extension? What I am looking for is a manual sorting option for the news. I have tried to activate it in the news listing module. But I can not sort manually.?

**Comment by fritzmg** [comment]
That's what I have already explained [here](https://github.com/fritzmg/contao-news-sorting/issues/7#issuecomment-993788244) ;).

Just to avoid further confusion:

* This extension provides additional sorting options for the **news list front end module**. So in the module's settings you will find additional options for the sorting of the generated news items.
* As mentioned in the README you can use the _Custom_ sort setting, which will sort the news by a custom order that you defined in the back end.
* To actually be able to sort the news in the back end (like you would be able to with content elements) you first need to set the sorting in your back end view to _Sorting value_ as shown in the screenshot above.

**Comment by wschwaiger** [comment]
OMG. Thank you! I did not get the last bit. Thank you for your patience.
