### ISSUE TITLE
Contao 4.13.23 - keine Manuelle Sortierung?

### ISSUE THREAD

**Issue by kalterwind** [fritzmg/contao-news-sorting#8]
Im Nachrichten Modul können die News nicht manuell sortiert werden (weder per Drag & Drop), noch per "Verschieben-Icon".

**Comment by fritzmg** [comment]
See the README:

> When using the Custom sort setting you can switch the sorting in the back end to Sorting value (do not forget to apply) and then sort the news articles via drag & drop in the back end.
